print("Testing imports...")
import cv2; print("cv2 OK")
import numpy; print("numpy OK")
import mediapipe; print("mediapipe OK")
import yaml; print("yaml OK")
import psutil; print("psutil OK")
import win32gui; print("win32gui OK")
import win32process; print("win32process OK")
from colorama import Fore, Style, init; print("colorama OK")
import threading; print("threading OK")
import time; print("time OK")
import sqlite3; print("sqlite3 OK")
print("All basic imports OK")
